package com.newhc.admin.common;


public interface ErrorCode {
	
	public String INVALID_REQUEST = "INVALID_REQUEST";	
	
	public String VALIDATE_CODE_NOT_MATCH = "VALIDATE_CODE_NOT_MATCH";
	
	public String USERNAME_OR_PASSWORD_IS_NULL = "USERNAME_OR_PASSWORD_IS_NULL";
	
	public String USERNAME_OR_PASSWORD_IS_FALSE = "USERNAME_OR_PASSWORD_IS_FALSE";
	
	public String DELETE_PARENT_CATEGORY_FALSE = "DELETE_PARENT_CATEGORY_FALSE";
	
	public String DELETE_PARENT_VIDEO_CATEGORY_FALSE ="DELETE_PARENT_VIDEO_CATEGORY_FALSE";
	
	public String DELETE_PARENT_MAGAZINE_CATEGORY_FALSE = "DELETE_PARENT_MAGAZINE_CATEGORY_FALSE";
	
	public String DELETE_PARENT_EHANDBOOK_CATEGORY_FALSE = "DELETE_PARENT_EHANDBOOK_CATEGORY_FALSE";
	
	
}

