package com.newhc.admin.entity.en;

import java.util.Date;

/**
 * ModelLink generated by MyEclipse Persistence Tools
 */

public class ModelLinkEn implements java.io.Serializable {

	// Fields

	private Integer id;

	private String name;

	private String logo;

	private String link;

	private Integer sequence;

	private Integer status;

	private Date createTime;

	private Date updateTime;

	private String creator;

	private String updator;

	// Constructors

	/** default constructor */
	public ModelLinkEn() {
	}

	/** minimal constructor */
	public ModelLinkEn(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public ModelLinkEn(Integer id, String name, String logo, String link,
			Integer sequence, Integer status, Date createTime, Date updateTime,
			String creator, String updator) {
		this.id = id;
		this.name = name;
		this.logo = logo;
		this.link = link;
		this.sequence = sequence;
		this.status = status;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.creator = creator;
		this.updator = updator;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLogo() {
		return this.logo;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}

	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	public Integer getSequence() {
		return this.sequence;
	}

	public void setSequence(Integer sequence) {
		this.sequence = sequence;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public String getUpdator() {
		return this.updator;
	}

	public void setUpdator(String updator) {
		this.updator = updator;
	}

}